### PR TITLE
Gulp security issues fixed

### PR DESCRIPTION
**Pull request by Mariyan96**
Updated all packages except babel-core which is on version 7 (stability issues)

### CODE REVIEW

**Comment by xavortm** [comment]
**Thank you** for the PR, @Mariyan96, will do the review and probably merge to master real soon 🔥

**Comment by xavortm** [comment]
@Mariyan96 Not working well for me. I don't want to have to run the setup using the `npm run gulp` command but just `gulp` instead.

With your next patch, post a quick guide on install + run commands so that I use it the way you've intended. Right now, if I run `npm run gulp`, it goes through the tasks and stops without watching or changes.

If I run `gulp` it outputs this:

```
[15:59:01] Using gulpfile ~/Sites/wordpress/wp-content/themes/DX-Starter/gulpfile.js
/Users/alex/.npm-packages/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/alex/.npm-packages/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (internal/process/next_tick.js:176:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

`gulp -v` outputs:

```
[16:06:06] CLI version 3.9.1
[16:06:06] Local version 4.0.0
```

Already checked this https://github.com/gulpjs/gulp-cli/issues/84

**Comment by Mariyan96** [comment]
I've fixed the problem (not starting the watch function), but I've encountered another problem:
 ```Error: watch assets/src/sass ENOSPC``` 
The problem is within Jest watching big number of files and their sizes. With my research I've found that this exist on Linux only because it has limited watchers. So to increase the number of watcher you need to run this command in the command prompt:
*echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p*

**Comment by Mariyan96** [comment]
Hey,
I've created new script to configure the global dependencies ( gulp, gulp-cli ). You just need to run *npm run projectConf* in the directory of the project.

**Pull request merged**
